### ISSUE TITLE
[playground] Parser definition error seem to break the playground

### ISSUE THREAD

**Issue by montymxb** [eclipse-langium/langium-website#130]
Using [this](https://langium.org/playground?grammar=OYJwhgthYgBAEgUwDbIPYHU0mQEwFD6IB2ALiAJ6wCyauKAXPrCzXSgJKmIQBUA3IQBm4YBBKk29ZFx5NWsAA6IQAZzTFVAagC8ABRXrivWAB9YoRIlIBLYsG06A4iCu37AwgbUb5rAOTKPsT%2BsMSQiDocACKCsPgubnbAfiz%2BSKhooUFGOgDa3kYMMQC6sP4AhP6C%2BAAWNrj0xLDcIBB2YMiwGADKDLAA9AA62gOCre3hXTH9A3kA%2BmAAtABeAIJLAFoleUMA7vMlvGOE9Y0kLSqTnTQAMvMAwgDy1NQAogByACqzQ8O8u1UQx6RwA-ENeH8Tmcmpc2h0uj17s9Xp8foM-n88gA9IbEIYgI4nIA&content=A4UwTgzg9gdgBAKSgCxgKFJWiCGMRpoASIANqVIijAITFkW751pA) Grammar produce a chevrotain parser definition error.

Now if one tries to edit the grammar to correct the syntax, model editor shows 'Loading...' but nothing happens. 

Browser also reports an error in the console: 
`Unhandled Promise Rejection: monaco-languageclient start was unsuccessful: Request initialize failed with message: Parser Definition Errors detected:`

**Comment by JohannesMeierSE** [comment]
@montymxb Your example works for me with the current playground.

**Comment by JohannesMeierSE** [comment]
But I detected the same behaviour with another [grammar](https://langium.org/playground?grammar=OYJwhgthYgBAEgUwDbIPYHU0mQEwFD6IB2ALiAJ6wCyauKAXPrC7IgB4AOIiAzrwEs0xXgGoAvAFEuPfkOKwAFAHIANMrYy%2Bg4WKla5wgJQAqANyFp3bfKatYAQVy4rsnQoA%2BNAK7JSAzmQKVxthWC8ANTBkb0QQw2ILfCcXA3c7VmREADNSfWsE2GVRDRABYAALPPj3C2pff0DgtNtmTJzqlrDlE1Lyqvy3eQsomLiu4gyWADdo2PEAOQBVagAhSQAlJIqBZxJYUkQQCAFiaNgMAGUGWAB6AB0xW4tD49Pz5bXNm9uAbQAGAC0AE4ALqiZ74V4nM7IWAASQAIj9fgB9MCAgBeDkBAC1Qb97gB3VGgkyQ-A7PYKaHvOHUAAyqIAwgB5ajUSQLAAqP3uDxMhN490uZIA-PcTPzIVT6DSjjDzpcmWyOVzeXd%2BfzfgA9e7Ee4gMkUoA&content=EwAg1CDMA0BQx1AKikA) which fails due to left-recursion.

The grammar editor shows no error message, the content editor is "Loading ..." or shows some content without language support.

**Comment by msujew** [comment]
@JohannesMeierSE I believe that it used to fail due to a statically identified lookahead ambiguity. Since switching to an LL(\*) lookahead, that's not an issue anymore.

**Comment by JohannesMeierSE** [comment]
Yes, failing of the grammar is expected and OK, but the user experience in the playground is bad, since as user I expect an error marker in the grammar editor and not a "no-response" with the error message hidden in the browser console ...

**Comment by spoenemann** [comment]
Here's an example of a user writing a grammar in the Playground and not seeing the "Ambiguous Alternatives Detected" parser error, which is only printed in the console:
https://github.com/eclipse-langium/langium/discussions/1259

We should make such parser validation errors visible in the Playground UI.

**Comment by spoenemann** [comment]
Clearing the assignee so anyone can take this. @Lotes feel free to take it back if you'd like to work on this.

**Comment by msujew** [comment]
By the way, I believe the original issue here as been resolved in https://github.com/eclipse-langium/langium-website/pull/171.

**Comment by Lotes** [comment]
As @msujew said: The original issue was resolved. I took the opportunity and wired out two open successor issues from this issue: #266 and #267
I will close this issue now.
