### ISSUE TITLE
Small Code Snippet Overflow

### ISSUE THREAD

**Issue by montymxb** [eclipse-langium/langium-website#148]
Seems code snippets can overflow a bit in the X coordinate for the docs. Here's an example from the [qualified name scoping guide](https://langium.org/guides/scoping/qualified-name/) (middle of the code snippet sticks over the right-hand edge).

![p1](https://user-images.githubusercontent.com/5070304/235852888-a5524dfc-8030-4dd1-aa5d-591e7e2b8786.jpg)

**Comment by bjthehun** [comment]
This issue appears to have been fixed by Pull Request #198 (PR #199 explains what has been done, namely making code blocks vertically scrollable):
![Screenshot 2024-04-11 at 13-24-35 Qualified Name Scoping](https://github.com/eclipse-langium/langium-website/assets/38729215/103302ee-c5c5-4d81-8f17-2c702f82d72c)

**Comment by montymxb** [comment]
Yep I was just peeking at this again and it looks good, thanks for pointing that out!
